config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :pedidos

      get "cosas/contarpedidos", as: 'contpedidos'
    end
  end

  resources :pedidos

  resources :subsubmenus

  resources :submenus

  resources :tipos

  resources :marcas

  resources :menus

  resources :galerias
  resources :productos do
    resources :galerias
  end

  get "principal/:producto_id/ver-producto/", to: "principal#ver_producto", as: "ver-producto"
  get "principal/productos/", to: "principal#productos", as: "ver-productos"
  get "dashboard", to: "dashboard#index", as: "dashboard"
  root 'principal#index'

  get 'principal/noticias'
  get 'principal/eventos'
  get 'principal/ubicacion'
  get 'principal/contacto'
  get 'principal/menusuperior'
  get 'principal/checkout'
  get "principal/quienes_somos/", to: "principal#quienes_somos", as: "quienes-somos"

  resources :noticias

  resources :categorias

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
    get 'edit' => 'devise/sessions#edit'

  end

end

app/views/shared/_dinamicmenusuperior.html.erb
<% @menus.each do |menu| %>
  <ul class="nav navbar-nav">
      <li>
          <% if menu.submenus.count > 0 %>
            <%= link_to "#{menu.nombremenu} <b class='caret'></b>".html_safe, ver_productos_path(menuid: menu.id),  "data-no-turbolink" => true, :'data-toggle'=>"dropdown", :class => 'dropdown-toggle' %>
            <ul class="dropdown-menu">
                <% if menu.submenus.count > 0 %>
                  <% menu.submenus.each do |submenu|%>
                    <% if submenu.subsubmenus.count > 0 %>
                      <li class="dropdown-submenu">
                          <%= link_to "#{submenu.nombremenu}".html_safe, ver_productos_path(submenuid: submenu.id),  "data-no-turbolink" => true, :'data-toggle'=>"dropdown", :class => 'dropdown-toggle' %>
                          <ul class="dropdown-menu">
                              <% submenu.subsubmenus.each do |subsubmenu|%>
                                <li><%= link_to "#{subsubmenu.nombremenu}".html_safe, ver_productos_path(subsubmenuid: subsubmenu.id),  "data-no-turbolink" => true %></li>
                              <% end %>
                          </ul>
                      </li>
                    <% else %>
                      <li><%= link_to "#{submenu.nombremenu}".html_safe, ver_productos_path(submenuid: submenu.id),  "data-no-turbolink" => true %></li>
                    <% end %>
                  <% end %>
                <% else %>
                <% end %>
            </ul>
          <% else %>
            <%= link_to "#{menu.nombremenu}".html_safe, ver_productos_path(menuid: menu.id),  "data-no-turbolink" => true %>
          <% end %>
      </li>
  </ul>
<% end %>

app/views/shared/_flashmessage.html.erb
<% if flash[:alert] %>
  <div class="alert alert-error alert-block">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>Aviso!</h4>
    <%= flash[:alert] %>
  </div>

<% end %>
<% if flash[:notice] %>
  <div class="alert alert-info alert-block">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>Aviso!</h4>
    <%= flash[:notice] %>
  </div>

<% end %>

app/views/shared/_listproducto.html.erb
<% @productos.each do |producto| %>
<div class="col-xs-3 col-sm-4 col-md-4" >
  <div class="col-item" style="margin-top: .5em;">
    <div class="photo">
      <% if producto.imagen.url == nil || producto.imagen.url == "" %>
fewefw
        <%= link_to  image_tag("camingsoon.png", :class => "img-responsive", :alt=>''), ver_producto_path(producto),  "data-no-turbolink" => true %>
      <% else %>

        <%= link_to  image_tag(producto.imagen, :class => "img-responsive", :alt=>''), ver_producto_path(producto),  "data-no-turbolink" => true %>
      <% end %>
    </div>
    <div class="info">
      <div class="row">
        <div class="price col-md-12 col-sm-6 col-xs-4">
          <h5>
            <%= link_to producto.nombre, ver_producto_path(producto),  "data-no-turbolink" => true %></h5>
          <h5 class="price-text-color">
            $<%= producto.costo %> <br /><%= producto.tpmoneda %></h5>
        </div>
        <!--<div class="rating hidden-sm col-md-6">-->
          <!--<i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">-->
        <!--</i><i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">-->
        <!--</i><i class="fa fa-star"></i>-->
        <!--</div>-->
      </div>
      <div class="separator clear-left">
        <p class="btn-add">
          <span style="font-size: 2em;" class="glyphicon glyphicon-shopping-cart" aria-hidden="true"  ng-click="oneclickadd('<%= producto.id %>')"  ></span><span> <span ng-click="oneclickadd('<%= producto.id %>')" style="color: #003399; padding: 10px;">Agregar</span></span></p>
        <p class="btn-details">
          <span style="font-size: 2em;" class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><%= link_to ' Mas Detalles', ver_producto_path(producto),  "data-no-turbolink" => true, :class => 'hidden-sm' %></p>
      </div>
      <div class="clearfix">
      </div>
    </div>
  </div>
</div>


<% end %>

app/views/shared/_menu.html.erb
<div class="navbar navbar-inverse" role="navigation" >
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">TijuanaGeek  <% if user_signed_in? %>
        - <small><%= current_user.email %> </small>  - <% end %> </a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Principal", root_path,  "data-no-turbolink" => true  %></li>
      <li><%= link_to "Quienes somos", quienes_somos_path,  "data-no-turbolink" => true  %></li>
      <li><%= link_to "Donde estamos", principal_ubicacion_path,  "data-no-turbolink" => true  %></li>
      <li><%= link_to "Contacto", principal_contacto_path,  "data-no-turbolink" => true  %></li>

    </ul>



    <!-- Left nav -->


    <ul class="nav navbar-nav navbar-right" >
        <li>
            <a class="btn btn-default btn-lg" data-no-turbolink="true" href="/principal/checkout?productos={{productosid}}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span><span class="badge ng-binding">{{productos.length}}</span> Articulos</a>

</li>
      <% if user_signed_in? %>
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mi Cuenta<b class="caret"></b></a>
          <ul class="dropdown-menu multi-level">
            <li> <%= link_to "Editar Cuenta", edit_user_registration_path %></li>
            <li> <%= link_to "Cerrar Sessión", destroy_user_session_path %></li>
            <% if current_user.roles.map(&:name) == ["Administrador"] %>
              <li class="divider"></li>
              <li> <%= link_to "Panel de control", dashboard_path %></li>
            <% end %>

          </ul>
        </li>
      <% else %>
        <li><%= link_to "Ingresar", new_user_session_path,  "data-no-turbolink" => true %></li>
        <li><%= link_to "Registrarme", new_user_registration_path,  "data-no-turbolink" => true %></li>
      <% end %>

    </ul>










  </div><!--/.nav-collapse -->
</div>

app/views/shared/_menuadmin.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TijuanaGeek  <% if user_signed_in? %>
          - <small><%= current_user.email %> </small>  - <% end %> </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Categorias", categorias_path,  "data-no-turbolink" => true  %></li>
        <li><%= link_to "Productos", productos_path,  "data-no-turbolink" => true  %></li>
        <li><%= link_to "Marcas", marcas_path,  "data-no-turbolink" => true  %></li>
        <li><%= link_to "Tipos", tipos_path,  "data-no-turbolink" => true  %></li>
        <li><%= link_to "Menu", menus_path %></li>
        <li><%= link_to "sub-Menu", submenus_path %></li>
        <li><%= link_to "subsub-Menu", subsubmenus_path %></li>


      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li> <%= link_to "Cerrar Sessión", destroy_user_session_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mi Cuenta <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Ingresar", new_user_session_path %></li>
              <li><%= link_to "Registrarme", new_user_registration_path %></li>



            </ul>
          </li>


        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_newadminmenu.html.erb
<div class="col-sm-3 col-md-2"   ng-controller="menu" ng-init="contpedidos()">

    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">
                    </span>Content</a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
                <ul class="list-group">
                    <li class="list-group-item"><span class="glyphicon glyphicon-pencil text-primary"></span>
                        <ul class="list-group">
                            <li class="list-group-item"><span class="glyphicon glyphicon-barcode text-primary"></span><%= link_to "Productos", productos_path,  "data-no-turbolink" => true  %></li>
                            <li class="list-group-item"><span class="glyphicon glyphicon-registration-mark text-success"></span><%= link_to "Marcas", marcas_path,  "data-no-turbolink" => true  %></li>
                            <li class="list-group-item"><span class="glyphicon glyphicon-file text-info"></span><%= link_to "Tipos", tipos_path,  "data-no-turbolink" => true  %></li>
                            <li class="list-group-item"><span class="glyphicon glyphicon glyphicon-usd text-success"></span><%= link_to "Pedidos", pedidos_path,  "data-no-turbolink" => true %><span class="badge">{{pedidos}}</span></li>


                        </ul>
                    </li>

                    <li class="list-group-item"><span class="glyphicon glyphicon-th-large text-success"></span><%= link_to "Menu", menus_path %></li>
                    <li class="list-group-item"><span class="glyphicon glyphicon-th-list text-info"></span><%= link_to "sub-Menu", submenus_path %></li>
                    <li class="list-group-item"> <span class="glyphicon glyphicon-th text-success"></span><%= link_to "subsub-Menu", subsubmenus_path %></li>

                </ul>
            </div>
        </div>


    </div>
</div>

app/views/shared/_treemenu.html.erb
<style>
    .submenus{
      font-size: 0.9em;
      color: #000000 !important;
    }
</style>
<% @menus.each do |menu| %>
  <ul class="tree">
      <li><%= link_to "#{menu.nombremenu}".html_safe, ver_productos_path(menuid: menu.id),  "data-no-turbolink" => true %>
      <% if menu.submenus.count > 0 %>
        <ul>
            <% if menu.submenus.count > 0 %>
              <% menu.submenus.each do |submenu|%>
                <% if submenu.subsubmenus.count > 0 %>
                  <li>
                      <%= link_to "#{submenu.nombremenu}".html_safe, ver_productos_path(submenuid: submenu.id),  "data-no-turbolink" => true, :class => 'submenus' %>
                      <ul>
                          <% submenu.subsubmenus.each do |subsubmenu|%>
                            <li><%= link_to "#{subsubmenu.nombremenu}".html_safe, ver_productos_path(subsubmenuid: subsubmenu.id),  "data-no-turbolink" => true %></li>
                          <% end %>
                      </ul>
                  </li>
                <% else %>
                  <li><%= link_to "#{submenu.nombremenu}".html_safe, ver_productos_path(submenuid: submenu.id),  "data-no-turbolink" => true %></li>
                <% end %>
              <% end %>
            <% else %>
            <% end %>
        </ul>
      <% else %>

      <% end %>

      </li>

  </ul>
<% end %>

<script>
  $.fn.extend({
    treed: function() {
      return this.each(function() {
        //initialize each of the top levels
        var tree = $(this);
        tree.addClass("tree");
        tree.find('li').has("ul").each(function () {
          var branch = $(this); //li with children ul
          branch.prepend("<i class='indicator glyphicon glyphicon-plus-sign'></i>");
          branch.addClass('branch');
          branch.on('click', function (e) {
            if (this == e.target) {
              var icon = $(this).children('i:first');
              icon.toggleClass("glyphicon-minus-sign glyphicon-plus-sign");
              $(this).children().children().toggle();
            }
          });
          branch.children().children().toggle();
        });
        //fire event from the dynamically added icon
        $('.branch .indicator, i').on('click',function(){
          $(this).closest('li').click();
        });
        //fire event to open branch if the li contains an anchor instead of text
//        $('.branch a').on('click',function(e){
//          $(this).closest('li').click();
//          e.preventDefault();
//        });
        //fire event to open branch if the li contains a button instead of text
        $('.branch button').on('click',function(e){
          $(this).closest('li').click();
          e.preventDefault();
        });
      });
    }
  });


  $('.tree').treed();
</script>