config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :pedidos

      get "cosas/contarpedidos", as: 'contpedidos'
    end
  end

  resources :pedidos

  resources :subsubmenus

  resources :submenus

  resources :tipos

  resources :marcas

  resources :menus

  resources :galerias
  resources :productos do
    resources :galerias
  end

  get "principal/:producto_id/ver-producto/", to: "principal#ver_producto", as: "ver-producto"
  get "principal/productos/", to: "principal#productos", as: "ver-productos"
  get "dashboard", to: "dashboard#index", as: "dashboard"
  root 'principal#index'

  get 'principal/noticias'
  get 'principal/eventos'
  get 'principal/ubicacion'
  get 'principal/contacto'
  get 'principal/menusuperior'
  get 'principal/checkout'
  get "principal/quienes_somos/", to: "principal#quienes_somos", as: "quienes-somos"

  resources :noticias

  resources :categorias

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
    get 'edit' => 'devise/sessions#edit'

  end

end

app/models/marca.rb
class Marca < ActiveRecord::Base
  has_many :productos

end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: [:show, :edit, :update, :destroy]
  respond_to :html
  before_action :authenticate_user!
  before_action :validarusuario
  layout 'admin'


  def validarusuario
    if current_user.roles.map(&:name) == ["Cliente"]
      authorize! :accion, User
    else

    end

  end

  def index
    @marcas = Marca.all
    respond_with(@marcas)
  end

  def show
    respond_with(@marca)
  end

  def new
    @marca = Marca.new
    respond_with(@marca)
  end

  def edit
  end

  def create
    @marca = Marca.new(marca_params)
    @marca.save
    respond_with(@marca)
  end

  def update
    @marca.update(marca_params)
    respond_with(@marca)
  end

  def destroy
    @marca.destroy
    respond_with(@marca)
  end

  private
    def set_marca
      @marca = Marca.find(params[:id])
    end

    def marca_params
      params.require(:marca).permit(:marca, :descripcion)
    end
end

app/views/marcas/_form.html.erb
<%= form_for(@marca) do |f| %>
  <% if @marca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
      <% @marca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marcas/edit.html.erb
<h1>Editing marca</h1>

<%= render 'form' %>

<%= link_to 'Show', @marca %> |
<%= link_to 'Back', marcas_path %>

app/views/marcas/index.html.erb
<h1>Listing marcas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Marca</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= marca.marca %></td>
        <td><%= marca.descripcion %></td>
        <td><%= link_to 'Show', marca %></td>
        <td><%= link_to 'Edit', edit_marca_path(marca) %></td>
        <td><%= link_to 'Destroy', marca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marca', new_marca_path %>

app/views/marcas/new.html.erb
<h1>New marca</h1>

<%= render 'form' %>

<%= link_to 'Back', marcas_path %>

app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @marca.marca %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @marca.descripcion %>
</p>

<%= link_to 'Edit', edit_marca_path(@marca) %> |
<%= link_to 'Back', marcas_path %>