config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :pedidos

      get "cosas/contarpedidos", as: 'contpedidos'
    end
  end

  resources :pedidos

  resources :subsubmenus

  resources :submenus

  resources :tipos

  resources :marcas

  resources :menus

  resources :galerias
  resources :productos do
    resources :galerias
  end

  get "principal/:producto_id/ver-producto/", to: "principal#ver_producto", as: "ver-producto"
  get "principal/productos/", to: "principal#productos", as: "ver-productos"
  get "dashboard", to: "dashboard#index", as: "dashboard"
  root 'principal#index'

  get 'principal/noticias'
  get 'principal/eventos'
  get 'principal/ubicacion'
  get 'principal/contacto'
  get 'principal/menusuperior'
  get 'principal/checkout'
  get "principal/quienes_somos/", to: "principal#quienes_somos", as: "quienes-somos"

  resources :noticias

  resources :categorias

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
    get 'edit' => 'devise/sessions#edit'

  end

end

app/models/subsubmenu.rb
class Subsubmenu < ActiveRecord::Base
  belongs_to :submenu
  has_and_belongs_to_many :productos
end

app/controllers/subsubmenus_controller.rb
class SubsubmenusController < ApplicationController
  before_action :set_subsubmenu, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :validarusuario
  before_action :set_dropdownlist, only: [:new, :edit, :update, :create]
  layout 'admin'
  respond_to :html


  def validarusuario
    # raise StandardError, "#{current_user.roles.map(&:name).inspect}"
    if current_user.has_role? :Cliente
      authorize! :accion, User
    else

    end
  end

  def index
    @subsubmenus = Subsubmenu.all
    respond_with(@subsubmenus)
  end

  def show
    respond_with(@subsubmenu)
  end

  def new
    @subsubmenu = Subsubmenu.new
    respond_with(@subsubmenu)
  end

  def edit
  end

  def create
    @subsubmenu = Subsubmenu.new(subsubmenu_params)
    @subsubmenu.save
    respond_with(@subsubmenu)
  end

  def update
    @subsubmenu.update(subsubmenu_params)
    respond_with(@subsubmenu)
  end

  def destroy
    @subsubmenu.destroy
    respond_with(@subsubmenu)
  end

  private
    def set_dropdownlist
      @submenus = Submenu.all
    end

    def set_subsubmenu
      @subsubmenu = Subsubmenu.find(params[:id])
    end

    def subsubmenu_params
      params.require(:subsubmenu).permit(:nombremenu, :submenu_id, :descripcion)
    end
end

app/views/subsubmenus/_form.html.erb
<%= form_for(@subsubmenu) do |f| %>
  <% if @subsubmenu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subsubmenu.errors.count, "error") %> prohibited this subsubmenu from being saved:</h2>

      <ul>
      <% @subsubmenu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombremenu %><br>
    <%= f.text_field :nombremenu %>
  </div>
  <div class="field">
    <%= f.label :submenu_id %><br>
    <%= f.select :submenu_id, @submenus.map {|comp| [comp.nombremenu, comp.id]}, {:include_blank => true}, :class=>"" %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subsubmenus/edit.html.erb
<h1>Editing subsubmenu</h1>

<%= render 'form' %>

<%= link_to 'Show', @subsubmenu %> |
<%= link_to 'Back', subsubmenus_path %>

app/views/subsubmenus/index.html.erb
<h1>Listing subsubmenus</h1>

<table>
  <thead>
    <tr>
      <th>Submenu</th>
      <th>Menu</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subsubmenus.each do |subsubmenu| %>
      <tr>
        <td><%= subsubmenu.nombremenu %></td>
        <td><%= subsubmenu.submenu_id %></td>
        <td><%= subsubmenu.descripcion %></td>
        <td><%= link_to 'Show', subsubmenu %></td>
        <td><%= link_to 'Edit', edit_subsubmenu_path(subsubmenu) %></td>
        <td><%= link_to 'Destroy', subsubmenu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subsubmenu', new_subsubmenu_path %>

app/views/subsubmenus/new.html.erb
<h1>New subsubmenu</h1>

<%= render 'form' %>

<%= link_to 'Back', subsubmenus_path %>

app/views/subsubmenus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Submenu:</strong>
  <%= @subsubmenu.nombremenu %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @subsubmenu.submenu_id %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @subsubmenu.descripcion %>
</p>

<%= link_to 'Edit', edit_subsubmenu_path(@subsubmenu) %> |
<%= link_to 'Back', subsubmenus_path %>