config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :pedidos

      get "cosas/contarpedidos", as: 'contpedidos'
    end
  end

  resources :pedidos

  resources :subsubmenus

  resources :submenus

  resources :tipos

  resources :marcas

  resources :menus

  resources :galerias
  resources :productos do
    resources :galerias
  end

  get "principal/:producto_id/ver-producto/", to: "principal#ver_producto", as: "ver-producto"
  get "principal/productos/", to: "principal#productos", as: "ver-productos"
  get "dashboard", to: "dashboard#index", as: "dashboard"
  root 'principal#index'

  get 'principal/noticias'
  get 'principal/eventos'
  get 'principal/ubicacion'
  get 'principal/contacto'
  get 'principal/menusuperior'
  get 'principal/checkout'
  get "principal/quienes_somos/", to: "principal#quienes_somos", as: "quienes-somos"

  resources :noticias

  resources :categorias

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
    get 'edit' => 'devise/sessions#edit'

  end

end

app/models/galeria.rb
class Galeria < ActiveRecord::Base
  belongs_to :producto

  mount_uploader :imagen, ImagenUploader

end

app/controllers/galerias_controller.rb
class GaleriasController < ApplicationController
  before_action :set_galeria, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  before_action :authenticate_user!
  layout 'admin'
  before_action :validarusuario


  def validarusuario
    if current_user.roles.map(&:name) == ["Cliente"]
      authorize! :accion, User
    else

    end

  end


  def index
    if params[:producto_id]
      @producto = Producto.find_by(id: params[:producto_id] )
      @galerias = Galeria.where(producto_id: params[:producto_id])

    else
      @galerias = Galeria.all
    end

    respond_with(@galerias)
  end

  def show
    respond_with(@galeria)
  end

  def new
    @galeria = Galeria.new
    respond_with(@galeria)
  end

  def edit
  end

  def create
    @galeria = Galeria.new(galeria_params)
    respond_to do |format|
      if @galeria.save
        format.html { redirect_to producto_galerias_path(producto_id: @galeria.producto_id), notice: 'Archivo was successfully created.' }
        format.json { render :show, status: :created, location: @galeria }
      else
        format.html { render :new }
        format.json { render json: @galeria.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @galeria.update(galeria_params)
        format.html { redirect_to producto_galerias_path(producto_id: @galeria.producto_id), notice: 'Archivo was successfully created.' }
        format.json { render :show, status: :created, location: @galeria }
      else
        format.html { render :new }
        format.json { render json: @galeria.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @galeria.destroy
    respond_to do |format|
      format.html { redirect_to producto_galerias_path(producto_id: params[:producto_id]), notice: 'Archivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_galeria
      @galeria = Galeria.find(params[:id])
    end

    def galeria_params
      params.require(:galeria).permit(:imagen, :producto_id)
    end
end

app/views/galerias/_form.html.erb
<%= form_for @galeria do |f| %>


  <p>
    <label>Imagen Adicional</label>
    <%= image_tag(@galeria.imagen_url) if @galeria.imagen? %><br />
    <%= f.file_field :imagen, :class=>"form-control", :required=>true %>
    <%= f.hidden_field :imagen_cache %><br />
  </p>

    <%= f.hidden_field :producto_id, :value=>params[:producto_id] %>

  <div class="actions">
    <%= f.submit "Agregar Imagen", :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/galerias/edit.html.erb
<h1>Editar Imagen</h1>

<%= render 'form' %>

app/views/galerias/index.html.erb
<h1>Galeria del producto<br /><small><%= @producto.nombre%></small></h1>

<%= link_to 'Agregar imagen', new_producto_galeria_path(params[:producto_id]), :class => "btn btn-primary" %>
<%= link_to 'Regresar al producto', producto_path(params[:producto_id]), :class => "btn btn-info" %>

<table class="table">
  <thead>
    <tr>
      <th>Imagen</th>

      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @galerias.each do |galeria| %>
      <tr>
        <td><%= image_tag(galeria.imagen_url, style: "width: 10%;") if galeria.imagen? %></td>
        <td>
          <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_producto_galeria_path(params[:producto_id], galeria), :class => "btn btn-default" %>
          <%= link_to link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, producto_galeria_path(params[:producto_id], galeria), method: :delete, data: { confirm: 'Eliminar esta imagen?' }, :class => "btn btn-default" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/galerias/new.html.erb
<h1>Agregando imagen</h1>

<%= render 'form' %>

app/views/galerias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Imagen:</strong>
  <%= @galerium.imagen %>
</p>

<p>
  <strong>Articulo:</strong>
  <%= @galerium.articulo_id %>
</p>

<%= link_to 'Edit', edit_galerium_path(@galerium) %> |
<%= link_to 'Back', galeria_path %>